src/abrigo_animais/shelter/urls.py
from django.urls import path

from .views import (
    AdoptionAnimalView,
    AdoptionDetailView,
    AdoptionListView,
    AnimalDetailView,
    AnimalListView,
    PartnerDetailView,
    PartnerListView,
    ShelterDetailView,
    ShelterHomeView,
    ShelterListView,
)


app_name = 'shelter'

urlpatterns = [
    path('', ShelterHomeView.as_view(), name='home'),
    path('adocoes/', AdoptionListView.as_view(), name="list_adoptions"),
    path(
        'adocoes/<uuid:id>',
        AdoptionDetailView.as_view(),
        name="detail_adoption",
    ),
    path('animais/', AnimalListView.as_view(), name="list_animals"),
    path(
        'animais/<uuid:id>', AnimalDetailView.as_view(), name="detail_animal"
    ),
    path(
        'animais/<uuid:id>/adotar',
        AdoptionAnimalView.as_view(),
        name="adoption_animal",
    ),
    path('abrigos/', ShelterListView.as_view(), name="list_shelters"),
    path(
        'abrigos/<uuid:id>', ShelterDetailView.as_view(), name="detail_shelter"
    ),
    path(
        'parceiros/',
        PartnerListView.as_view(),
        name="list_partners",
    ),
    path(
        'parceiros/<uuid:id>',
        PartnerDetailView.as_view(),
        name="detail_partner",
    ),
]

src/abrigo_animais/urls.py
"""
URL configuration for abrigo_animais project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path
from django.views.generic.base import RedirectView

from abrigo_animais.core.views import LoginView


urlpatterns = (
    [
        path(
            '', RedirectView.as_view(pattern_name="shelter:home"), name='home'
        ),
        path('admin/', admin.site.urls),
        path('logout/', LogoutView.as_view(), name='logout'),
        path('login/', LoginView.as_view(), name='login'),
        path(
            'social-auth/',
            include('social_django.urls', namespace='social-auth'),
        ),
        path(
            'abrigo/',
            include('abrigo_animais.shelter.urls', namespace='shelter'),
        ),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # noqa
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # noqa
)

# handler500 = 'rest_framework.exceptions.server_error'
# handler404 = 'cog_platform.exceptions.page_not_found'

src/abrigo_animais/core/models/address.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from .base import BaseModel


class AddressModel(BaseModel):

    street = models.CharField(max_length=250, verbose_name=_('Street'))
    number = models.CharField(max_length=20, verbose_name=_('Number'))
    complement = models.CharField(
        max_length=250, verbose_name=_('Complement'), blank=True, null=True
    )
    neighborhood = models.CharField(
        max_length=250, verbose_name=_('Neighborhood')
    )
    city = models.CharField(max_length=250, verbose_name=_('City'))
    state = models.CharField(max_length=250, verbose_name=_('State'))
    zip_code = models.CharField(max_length=9, verbose_name=_('Zip code'))

    class Meta:
        abstract = True
        verbose_name = _('Address')
        verbose_name_plural = _('Addresses')

src/abrigo_animais/core/models/base.py
import uuid
from typing import Any

from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class BaseModel(models.Model):  # type: ignore

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name=_('Created at')
    )
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name=_('Updated at')
    )

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_created_by",
        related_query_name="%(app_label)s_%(class)ss_created_by",
        default=None,
        null=True,
        verbose_name=_('Created by'),
    )
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_updated_by",
        related_query_name="%(app_label)s_%(class)ss_updated_by",
        default=None,
        null=True,
        verbose_name=_('Updated by'),
    )

    class Meta:
        abstract = True
        ordering = ['id']

    def save(self, *args: Any, **kwargs: Any) -> None:
        self.updated_at = timezone.now()
        if self.created_by_id is None:
            self.created_by = self.updated_by
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f"<{self.__class__.__name__} id={self.id}>"

src/abrigo_animais/core/models/contact.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from .base import BaseModel


class ContactModel(BaseModel):

    class ContactType(models.TextChoices):  # type: ignore
        EMAIL = 'EMAIL', _('Email')
        PHONE = 'PHONE', _('Phone')
        WHATSAPP = 'WHATSAPP', _('WhatsApp')
        OTHER = 'OTHER', _('Other')

    type = models.CharField(
        max_length=20,
        choices=ContactType.choices,
        verbose_name=_('Type'),
        default=ContactType.OTHER,
    )
    value = models.CharField(max_length=250, verbose_name=_('Value'))

    class Meta:
        abstract = True
        verbose_name = _('Contact')
        verbose_name_plural = _('Contacts')

src/abrigo_animais/core/views.py
from typing import Any

from django.urls import reverse
from django.views.generic.base import RedirectView


class LoginView(RedirectView):  # type: ignore
    pattern_name = "social-auth:begin"

    def get_redirect_url(self, *args: Any, **kwargs: Any) -> Any:
        return reverse(self.pattern_name, args=['google-oauth2'])

src/abrigo_animais/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Housing Animals</title>
    
    <!-- Bootstrap CSS -->
    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/base.css' %}" rel="stylesheet">
    
    {% block 'head' %}{% endblock %}
    <title>{% block 'title' %}{% endblock %} - Abrigo de Animais</title>

  </head>
  <body>
    <header data-bs-theme="dark">
      {% include 'core/navbar.html' %}
    </header>
      {% block 'main_content' %}
      {% endblock %}
      
      <hr class="featurette-divider">
      {% include 'core/footer.html' %}

      <!-- Scripts do Bootstrap e outros -->
      <script 
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js" 
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" 
        crossorigin="anonymous">
      </script>
      <script>window.jQuery || document.write('<script src="{% static 'core/js/vendor/jquery-slim.min.js' %}"><\/script>')</script>
      <script src="{% static 'core/js/vendor/popper.min.js' %}"></script>
      <script src="{% static 'core/js/bootstrap.min.js' %}"></script>      
  </body>
</html>

src/abrigo_animais/core/templates/core/footer.html
<div class="site-footer">
    <div class="container">
        <div class="row text-center">
            <p>Desenvolvido por Camila Lima • 2024</p>
        </div>
        <ul class="icon">
            <li>
                <a class="github" href="https://github.com/" target="_blank">
                    <i class="devicon-github-original-wordmark"></i>
                </a>
            </li>
            <li>
                <a class="linkedin" href="https://www.linkedin.com/" target="_blank">
                    <i class="devicon-linkedin-plain"></i>
                </a>
            </li>
        </ul>
    </div>
</div>

src/abrigo_animais/core/templates/core/navbar.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark py-3">
    <div class="container-fluid">
        <img src="{% static 'core/img/animal3.png' %}" alt="Logo" width="60" height="60">
        <a class="navbar-brand" href="/">Housing Animals</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'shelter:list_animals' %}">Animais Disponíveis</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'shelter:list_adoptions' %}">Animais Adotados</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'shelter:list_partners' %}">Parceiros</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'shelter:list_shelters' %}">Abrigos</a>
                </li>
            </ul>
            {% if request.user.is_authenticated %}
                <div class="navbar-nav ms-auto">
                    <a class="nav-link a-white">Olá, {{ user.username }}</a>
                    <form method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button type="submit">Sair</button>
                    </form>
                </div>
            {% else %}
                <div class="navbar-nav ms-auto">
                    <a class="nav-link a-white" href="{% url 'social:begin' 'google-oauth2' %}">
                        <i class="fa fa-google"></i>Login
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
</nav>