src/abrigo_animais/shelter/urls.py
from django.urls import path

from .views import (
    AdoptionAnimalView,
    AdoptionDetailView,
    AdoptionListView,
    AnimalDetailView,
    AnimalListView,
    PartnerDetailView,
    PartnerListView,
    ShelterDetailView,
    ShelterHomeView,
    ShelterListView,
)


app_name = 'shelter'

urlpatterns = [
    path('', ShelterHomeView.as_view(), name='home'),
    path('adocoes/', AdoptionListView.as_view(), name="list_adoptions"),
    path(
        'adocoes/<uuid:id>',
        AdoptionDetailView.as_view(),
        name="detail_adoption",
    ),
    path('animais/', AnimalListView.as_view(), name="list_animals"),
    path(
        'animais/<uuid:id>', AnimalDetailView.as_view(), name="detail_animal"
    ),
    path(
        'animais/<uuid:id>/adotar',
        AdoptionAnimalView.as_view(),
        name="adoption_animal",
    ),
    path('abrigos/', ShelterListView.as_view(), name="list_shelters"),
    path(
        'abrigos/<uuid:id>', ShelterDetailView.as_view(), name="detail_shelter"
    ),
    path(
        'parceiros/',
        PartnerListView.as_view(),
        name="list_partners",
    ),
    path(
        'parceiros/<uuid:id>',
        PartnerDetailView.as_view(),
        name="detail_partner",
    ),
]

src/abrigo_animais/urls.py
"""
URL configuration for abrigo_animais project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path
from django.views.generic.base import RedirectView

from abrigo_animais.core.views import LoginView


urlpatterns = (
    [
        path(
            '', RedirectView.as_view(pattern_name="shelter:home"), name='home'
        ),
        path('admin/', admin.site.urls),
        path('logout/', LogoutView.as_view(), name='logout'),
        path('login/', LoginView.as_view(), name='login'),
        path(
            'social-auth/',
            include('social_django.urls', namespace='social-auth'),
        ),
        path(
            'abrigo/',
            include('abrigo_animais.shelter.urls', namespace='shelter'),
        ),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # noqa
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # noqa
)

# handler500 = 'rest_framework.exceptions.server_error'
# handler404 = 'cog_platform.exceptions.page_not_found'

src/abrigo_animais/core/models/contact.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from .base import BaseModel


class ContactModel(BaseModel):

    class ContactType(models.TextChoices):  # type: ignore
        EMAIL = 'EMAIL', _('Email')
        PHONE = 'PHONE', _('Phone')
        WHATSAPP = 'WHATSAPP', _('WhatsApp')
        OTHER = 'OTHER', _('Other')

    type = models.CharField(
        max_length=20,
        choices=ContactType.choices,
        verbose_name=_('Type'),
        default=ContactType.OTHER,
    )
    value = models.CharField(max_length=250, verbose_name=_('Value'))

    class Meta:
        abstract = True
        verbose_name = _('Contact')
        verbose_name_plural = _('Contacts')

src/abrigo_animais/shelter/models/adoptions.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from abrigo_animais.core.models import BaseModel


class AdoptionModel(BaseModel):
    class AdoptionStatus(models.TextChoices):  # type: ignore
        PENDING = 'pending', _('Pending')
        APPROVED = 'approved', _('Approved')
        REJECTED = 'rejected', _('Rejected')
        CANCELED = 'canceled', _('Canceled')

    animal = models.ForeignKey('shelter.AnimalModel', on_delete=models.CASCADE)
    responsible = models.ForeignKey(
        'shelter.ResponsibleModel', on_delete=models.CASCADE
    )
    status = models.CharField(
        max_length=50,
        choices=AdoptionStatus.choices,
        default=AdoptionStatus.PENDING,
    )

    class Meta:
        verbose_name = _('Adoption')
        verbose_name_plural = _('Adoptions')

    def __str__(self) -> str:
        return f'{self.animal} - {self.responsible} - {self.status}'

src/abrigo_animais/shelter/models/animals.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from abrigo_animais.core.models import BaseModel


class AnimalModel(BaseModel):
    class AnimalSpecie(models.TextChoices):  # type: ignore
        DOG = 'DOG', _('Dog')
        CAT = 'CAT', _('Cat')
        BIRD = 'BIRD', _('Bird')
        RODENT = 'RODENT', _('Rodent')
        OUTHER = 'OUTHER', _('Other')

    class AnimalSize(models.TextChoices):  # type: ignore
        SMALL = 'SMALL', _('Small')
        MEDIUM = 'MEDIUM', _('Medium')
        LARGE = 'LARGE', _('Large')

    shelter = models.ForeignKey(
        'shelter.ShelterModel', on_delete=models.CASCADE
    )
    name = models.CharField(max_length=250, verbose_name=_('Name'))
    age = models.IntegerField(verbose_name=_('Age'))
    breed = models.CharField(max_length=250, verbose_name=_('Breed'))
    specie = models.CharField(
        max_length=50,
        choices=AnimalSpecie.choices,
        default=AnimalSpecie.OUTHER,
        verbose_name=_('Specie'),
    )
    size = models.CharField(
        choices=AnimalSize.choices,
        max_length=50,
        verbose_name=_('Size'),
        default=AnimalSize.MEDIUM,
    )
    weight = models.FloatField(verbose_name=_('Weight'))
    photo = models.ImageField(upload_to='animals/', verbose_name=_('Photo'))

    class Meta:
        verbose_name = _('Animal')
        verbose_name_plural = _('Animals')

    def __str__(self) -> str:
        return f'{self.specie} {self.breed} {self.name}'

src/abrigo_animais/shelter/models/cares.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from abrigo_animais.core.models import BaseModel


class CareModel(BaseModel):
    class CareType(models.TextChoices):  # type: ignore
        FOOD = 'FOOD', _('Food')
        DRUG = 'DRUG', _('Drug')
        OTHER = 'OTHER', _('Other')

    animal = models.ForeignKey('shelter.AnimalModel', on_delete=models.CASCADE)
    care_type = models.CharField(
        max_length=50,
        choices=CareType.choices,
        verbose_name=_('Care type'),
        default=CareType.OTHER,
    )
    description = models.TextField(verbose_name=_('Description'))

    class Meta:
        verbose_name = _('Care')
        verbose_name_plural = _('Cares')

src/abrigo_animais/shelter/models/partners.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from abrigo_animais.core.models import AddressModel, BaseModel, ContactModel


class PartnerModel(BaseModel):
    name = models.CharField(max_length=250, verbose_name=_('Name'))
    description = models.TextField(
        verbose_name=_('Description'), blank=True, null=True
    )
    shelter = models.ForeignKey(
        'shelter.ShelterModel', on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = _('Partner')
        verbose_name_plural = _('Partners')

    def __str__(self) -> str:
        return f'Partner {self.name}'


class PartnerContactModel(ContactModel):
    partner = models.ForeignKey(
        'shelter.PartnerModel',
        on_delete=models.CASCADE,
        verbose_name=_('Partner'),
        related_name='contacts',
    )

    class Meta:
        verbose_name = _('Partner Contact')
        verbose_name_plural = _('Partner Contacts')


class PartnerAddressModel(AddressModel):
    partner = models.ForeignKey(
        'shelter.PartnerModel',
        on_delete=models.CASCADE,
        verbose_name=_('Partner'),
        related_name='addresses',
    )

    class Meta:
        verbose_name = _('Partner Address')
        verbose_name_plural = _('Partner Addresses')

src/abrigo_animais/shelter/models/responsibles.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _

from abrigo_animais.core.models import AddressModel, BaseModel, ContactModel


class ResponsibleModel(BaseModel):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name=_('User'),
    )

    class Meta:
        verbose_name = _('Responsible')
        verbose_name_plural = _('Responsibles')

    def __str__(self) -> str:
        return f'{self.user}'


class ResponsibleContactModel(ContactModel):
    responsible = models.ForeignKey(
        'shelter.ResponsibleModel',
        on_delete=models.CASCADE,
        verbose_name=_('Responsible'),
        related_name='contacts',
    )

    class Meta:
        verbose_name = _('Responsible Contact')
        verbose_name_plural = _('Responsible Contacts')


class ResponsibleAddressModel(AddressModel):
    responsible = models.ForeignKey(
        'shelter.ResponsibleModel',
        on_delete=models.CASCADE,
        verbose_name=_('Responsible'),
        related_name='addresses',
    )

    class Meta:
        verbose_name = _('Responsible Address')
        verbose_name_plural = _('Responsible Addresses')

src/abrigo_animais/shelter/models/shelters.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from abrigo_animais.core.models import AddressModel, BaseModel, ContactModel


class ShelterModel(BaseModel):
    name = models.CharField(max_length=250, verbose_name=_('Name'))
    description = models.TextField(verbose_name=_('Description'))
    website = models.URLField(verbose_name=_('Website'))
    photo = models.ImageField(upload_to='shelters/', verbose_name=_('Photo'))

    class Meta:
        verbose_name = _('Shelter')
        verbose_name_plural = _('Shelters')

    def __str__(self) -> str:
        return f'Shelter {self.name}'


class ShelterContactModel(ContactModel):
    shelter = models.ForeignKey(
        'shelter.ShelterModel',
        on_delete=models.CASCADE,
        verbose_name=_('Shelter'),
        related_name='contacts',
    )

    class Meta:
        verbose_name = _('Shelter Contact')
        verbose_name_plural = _('Shelter Contacts')


class ShelterAddressModel(AddressModel):
    shelter = models.ForeignKey(
        'shelter.ShelterModel',
        on_delete=models.CASCADE,
        verbose_name=_('Shelter'),
        related_name='addresses',
    )

    class Meta:
        verbose_name = _('Shelter Address')
        verbose_name_plural = _('Shelter Addresses')

src/abrigo_animais/shelter/forms/responsibles.py
from django import forms

from abrigo_animais.shelter.models import (
    ResponsibleAddressModel,
    ResponsibleContactModel,
    ResponsibleModel,
)


class ResponsibleContactForm(forms.ModelForm):  # type: ignore
    class Meta:
        model = ResponsibleContactModel
        exclude = ['created_at', 'updated_at', 'created_by', 'updated_by']


class ResponsibleAddressForm(forms.ModelForm):  # type: ignore
    class Meta:
        model = ResponsibleAddressModel
        exclude = ['created_at', 'updated_at', 'created_by', 'updated_by']


# Definindo os inlines usando inlineformset_factory
ResponsibleContactFormSet = forms.inlineformset_factory(
    ResponsibleModel,
    ResponsibleContactModel,
    form=ResponsibleContactForm,
    extra=1,
)

ResponsibleAddressFormSet = forms.inlineformset_factory(
    ResponsibleModel,
    ResponsibleAddressModel,
    form=ResponsibleAddressForm,
    extra=1,
)

src/abrigo_animais/shelter/views/adoption_animal.py
from typing import Any

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic.base import TemplateView

from ..forms import ResponsibleAddressFormSet, ResponsibleContactFormSet
from ..models import AdoptionModel, AnimalModel, ResponsibleModel


class AdoptionAnimalView(LoginRequiredMixin, TemplateView):  # type: ignore
    login_url = settings.LOGIN_URL
    redirect_field_name = "redirect_to"
    template_name = "shelter/adoption_animal.html"

    def get(
        self, request: HttpRequest, *args: Any, **kwargs: Any
    ) -> HttpResponse:
        context = {
            'animal': AnimalModel.objects.get(pk=kwargs['id']),
            'contact_formset': ResponsibleContactFormSet(),
            'address_formset': ResponsibleAddressFormSet(),
        }

        return self.render_to_response(context)

    def post(
        self, request: HttpRequest, *args: Any, **kwargs: Any
    ) -> HttpResponse:
        animal = AnimalModel.objects.get(pk=kwargs['id'])
        contact_formset = ResponsibleContactFormSet(request.POST)
        address_formset = ResponsibleAddressFormSet(request.POST)

        if contact_formset.is_valid() and address_formset.is_valid():
            responsible, _ = ResponsibleModel.objects.get_or_create(
                user=request.user
            )
            contact_formset.instance = responsible
            contact_formset.save()

            address_formset.instance = responsible
            address_formset.save()

            adoption = AdoptionModel.objects.create(
                animal=animal, responsible=responsible
            )
            return redirect(
                reverse('shelter:detail_adoption', args=[adoption.id])
            )

        context = {
            'animal': animal,
            'contact_formset': contact_formset,
            'address_formset': address_formset,
        }
        return self.render_to_response(context)

src/abrigo_animais/shelter/views/adoptions.py
from typing import Any

from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from ..models import AdoptionModel


class AdoptionListView(ListView):  # type: ignore
    model = AdoptionModel
    template_name = "shelter/adoption_list.html"
    paginate_by = 10


class AdoptionDetailView(DetailView):  # type: ignore
    model = AdoptionModel
    template_name = "shelter/adoption_detail.html"

    def get_object(self) -> Any:
        return self.model.objects.get(pk=self.kwargs['id'])

src/abrigo_animais/shelter/views/animals.py
from typing import Any

from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from ..models import AnimalModel


class AnimalListView(ListView):  # type: ignore
    queryset = AnimalModel.objects.filter(adoptionmodel__isnull=True)
    template_name = "shelter/animal_list.html"
    paginate_by = 10


class AnimalDetailView(DetailView):  # type: ignore
    model = AnimalModel
    template_name = "shelter/animal_detail.html"

    def get_object(self) -> Any:
        return self.model.objects.get(pk=self.kwargs['id'])

src/abrigo_animais/shelter/views/partners.py
from typing import Any

from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from ..models import PartnerModel


class PartnerListView(ListView):  # type: ignore
    model = PartnerModel
    template_name = "shelter/partner_list.html"
    paginate_by = 10


class PartnerDetailView(DetailView):  # type: ignore
    model = PartnerModel
    template_name = "shelter/partner_detail.html"

    def get_object(self) -> Any:
        return self.model.objects.get(pk=self.kwargs['id'])

src/abrigo_animais/shelter/views/shelter.py
from typing import Any

from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from ..models import ShelterModel


class ShelterHomeView(TemplateView):  # type: ignore
    template_name = "shelter/shelter_home.html"


class ShelterListView(ListView):  # type: ignore
    model = ShelterModel
    template_name = "shelter/shelter_list.html"
    paginate_by = 10


class ShelterDetailView(DetailView):  # type: ignore
    model = ShelterModel
    template_name = "shelter/shelter_detail.html"

    def get_object(self) -> Any:
        return self.model.objects.get(pk=self.kwargs['id'])

src/abrigo_animais/shelter/views/shelters.py
from typing import Any

from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from ..models import ShelterModel


class ShelterHomeView(TemplateView):  # type: ignore
    template_name = "shelter/shelter_home.html"


class ShelterListView(ListView):  # type: ignore
    model = ShelterModel
    template_name = "shelter/shelter_list.html"
    paginate_by = 10


class ShelterDetailView(DetailView):  # type: ignore
    model = ShelterModel
    template_name = "shelter/shelter_detail.html"

    def get_object(self) -> Any:
        return self.model.objects.get(pk=self.kwargs['id'])

src/abrigo_animais/shelter/templates/shelter/adoption_detail.html
{% extends "core/base.html" %}
{% load static %}
{% block 'title' %}
Página de detalhes
{% endblock %}

{% block 'main_content' %}
<div class="div-body">
    <div class="container classic-list">
        <h1 class="text-center h1-title">Veja todos os detalhes sobre {{ object.animal.name }} e {{ object.responsible.user}}</h1>
        <div class="row justify-content-center">
            <div class="col-4 ">
                <img src="{{ object.animal.photo.url }}" class="w-100 img-objects card-detail" alt="...">
            </div>
            <div class="col-4">
                <strong>Responsável:</strong> {{ object.responsible.user}}<br>
                <strong>Nome:</strong> {{ object.animal.name }}<br>
                <strong>Idade:</strong> {{ object.animal.age }}<br>
                <strong>Raça:</strong> {{ object.animal.breed }}<br>
                <strong>Espécie:</strong> {{ object.animal.get_specie_display }}<br>
                <strong>Tamanho:</strong> {{ object.animal.get_size_display }}<br>
                <strong>Peso:</strong> {{ object.animal.weight }}<br>
                <strong>Cuidados Especiais:</strong>
                {% for care in object.animal.caremodel_set.all %}
                    <p>Tipo de cuidado: {{ care.get_care_type_display }}</p>
                    <p>Detalhes: {{ care.description }}</p>
                {% endfor %}
                <br>
            </div>
        </div>
    </div>
    <!-- <div class="container text-center div-button link-adoption">
        <a class="btn-primary btn-lg btn-enviar" href="" >
            Solicitar sua adoção
        </a>
    </div> -->
</div>
    
{% endblock %}

src/abrigo_animais/shelter/templates/shelter/animal_detail.html
{% extends "core/base.html" %}
{% load static %}
{% block 'title' %}
Página de detalhes
{% endblock %}

{% block 'main_content' %}
<div class="div-body">
    <div class="container classic-list">
        <h1 class="text-center h1-title">Veja todos os detalhes sobre {{ object.name }}</h1>
        <div class="row justify-content-center">
            <div class="col-4 ">
                <img src="{{ object.photo.url }}" class="w-100 img-objects card-detail" alt="...">
            </div>
            <div class="col-4">
                <strong>Nome:</strong> {{ object.name }}<br>
                <strong>Espécie:</strong> {{ object.get_specie_display }}<br>
                <strong>Raça:</strong> {{ object.breed }}<br>
                <strong>Peso:</strong> {{ object.weight }} kg <br>
                <strong>Porte:</strong> {{ object.get_size_display }}<br>
                <strong>Cuidados Especiais:</strong>
                {% for care in object.caremodel_set.all %}
                    <p>Tipo de cuidado: {{ care.get_care_type_display }}</p>
                    <p>Detalhes: {{ care.description }}</p>
                {% endfor %}
                <br>
                <strong>Abrigo Associado:</strong> {{ object.shelter.name }}<br>
            </div>
        </div>
    </div>
    <div class="container text-center div-button link-adoption">
        <a class="btn-primary btn-lg btn-enviar" href="{% url 'shelter:adoption_animal' object.id %}" >
            Solicitar adoção de {{ object.name }}
        </a>
    </div>
</div>
    
{% endblock %}

src/abrigo_animais/shelter/templates/shelter/animal_list.html
{% extends "core/base.html" %}
{% load static %}
{% block 'title' %}
Animais para adoção
{% endblock %}

{% block 'main_content' %}

<link href="{% static 'core/css/base.css' %}" rel="stylesheet">

<div class="classic-list">
<div class="h1-title ">
    <h1 class="text-center">Animais para adoção</h1>
</div>
<div class="row row-cols-1 row-cols-md-3 g-4 card-total-animal">
    {% for animal in object_list %}
    <div class="col">
        <div class="card h-100 card-all card-total">
            <img width="100%" src="{{ animal.photo.url }}" class="card-img-top custom-image card-animal" alt="...">
            <a href="{% url 'shelter:detail_animal' animal.id %}" class="btn-enviar text-center card-link">
                Conheça {{ animal.name }}</a>
        </div>
    </div>
    {% empty %}
    <div class="container justify-content-center">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h5 class="text-center">Não encontrado.</h5>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
</div>



{% endblock %}

src/abrigo_animais/shelter/templates/shelter/partner_detail.html
{% extends "core/base.html" %}
{% load static %}
{% block 'title' %}
Página de detalhes do Pareceiro
{% endblock %}

<link href="{% static 'core/css/base.css' %}" rel="stylesheet">

{% block 'main_content' %}
<div class="div-body">
    <div class="container classic-list">
        <h1 class="text-center h1-title">Veja todos os detalhes sobre {{ object.name }}</h1>
        <div class="row justify-content-center">
            <div class="col-4 card-list">
                <strong>Nome:</strong> {{ object.name }}<br>
                <strong>Descrição:</strong> {{ object.description }}<br>
                <strong>Abrigo Associado:</strong>
                    <a href="{% url 'shelter:detail_shelter' object.shelter.id %}">
                        {{ object.shelter.name }}<br>
                    </a>
                <strong>Contato:</strong> 
                {% for contact in object.contacts.all %}
                <p>Tipo de Contato: {{ contact.get_type_display }}</p>
                <p>Dados do Contato: {{ contact.value }}</p>
            {% endfor %}
            </div>
        </div>
    </div>
</div>
    
{% endblock %}

src/abrigo_animais/shelter/templates/shelter/shelter_donation.html
{% extends "core/base.html" %}
{% load static %}
{% block 'title' %}
Página de doações para o Abrigo
{% endblock %}

<link href="{% static 'core/css/base.css' %}" rel="stylesheet">

{% block 'main_content' %}
<div class="div-body">
    <div class="container classic-list">
        <h1 class="text-center h1-title">Veja todos os detalhes sobre {{ object.name }}</h1>
        <div class="row justify-content-center">
            <div class="col-4">
                <strong>Nome:</strong> {{ object.name }}<br>
                
            </div>
        </div>
    </div>
</div>
    
{% endblock %}

src/abrigo_animais/shelter/templates/shelter/shelter_home.html
{% extends "core/base.html" %}
{% load static %}
{% block 'title' %}HOME{% endblock %}

{% block 'main_content' %}
<div class="classic-list">
<div id="carouselExample" class="carousel slide">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'core/img/cachorro1.jpg' %}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="{% static 'core/img/cachorro2.jpg' %}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="{% static 'core/img/cachorro3.jpg' %}" class="d-block w-100" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
</div>

<div class="container marketing mt-5">
    <div class="row">
        <div class="col-lg-4">
            <div style="width: 140px; height: 140px; background: var(--bs-secondary-color);" class="rounded-circle">
                <img src="{% static 'core/img/cachorro2.jpg' %}" alt="..." class="rounded-circle"
                    style="width: 100%; height: 100%; object-fit: cover;">
            </div>
            <h2 class="fw-normal">Animais para Adoção</h2>
            <p>
                <a class="btn btn-secondary card-link" href="{% url 'shelter:list_animals' %}">Saiba mais &raquo;</a></p>
        </div>
        <div class="col-lg-4">
            <div style="width: 140px; height: 140px; background: var(--bs-secondary-color);" class="rounded-circle">
                <img src="{% static 'core/img/veterinario.jpg' %}" alt="..." class="rounded-circle"
                    style="width: 100%; height: 100%; object-fit: cover;">
            </div>
            <h2 class="fw-normal">Parceiros</h2>
            <p>
                <a class="btn btn-secondary card-link" href="{% url 'shelter:list_partners' %}">Saiba mais &raquo;</a></p>
        </div>
        <div class="col-lg-4">
            <div style="width: 140px; height: 140px; background: var(--bs-secondary-color);" class="rounded-circle">
                <img src="{% static 'core/img/racao.jpg' %}" alt="..." class="rounded-circle"
                    style="width: 100%; height: 100%; object-fit: cover;">
            </div>
            <h2 class="fw-normal">Abrigos</h2>
            <p><a class="btn btn-secondary card-link" href="{% url 'shelter:list_shelters' %}">Saiba mais &raquo;</a></p>
        </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7 order-md-2">
            <div class="bd-placeholder-img-lg featurette-image img-fluid mx-auto">
                <img src="{% static 'core/img/abrigo.jpg' %}" alt="..." class="img-fluid">
            </div>
                    </div>
        <div class="col-md-5 order-md-1">
            <h2 class="featurette-heading fw-normal lh-1">Como surgimos: </h2>
            <p class="lead">O projeto Housing Animals é uma iniciativa inspiradora que teve origem em São Paulo, no ano de 2018. Sob a coordenação da dedicada protetora Maria Santos, que já tinha um abrigo anteriormente, mas com um espaço limitado para apenas 20 animais. Diante da crescente demanda e da necessidade de expandir sua capacidade de acolhimento, Maria decidiu dar um passo adiante e fundar o Housing Animals.</p>

            <br>
                
            <p class="lead">O novo abrigo foi projetado para proporcionar um lar temporário para
                 animais em situação de vulnerabilidade, oferecendo-lhes cuidados médicos, 
                 alimentação adequada, abrigo confortável e, acima de tudo, muito amor e atenção. Maria e sua equipe trabalharam incansavelmente para transformar o sonho do Housing Animals em realidade, mobilizando voluntários, arrecadando doações e estabelecendo parcerias com veterinários e outros profissionais dedicados ao bem-estar animal.</p>
                
        </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading fw-normal lh-1">Nossa missão: </h2>
            <p class="lead">Buscamos oferecer um ambiente seguro e acolhedor para o maior 
                número possível de animais desabrigados, 
                o Housing Animals foi concebido com a missão de ampliar sua capacidade de 
                acolhimento e estabelecer parcerias com outros abrigos e organizações protetoras de animais.</p>
                <br>
                <p class="lead">   Queremos mudar o destino dos animais abandonados e rejeitados, encaminhando-os para adoção. Mas sabemos que nem sempre os finais felizes acontecem. Por isso, nos dedicamos a proporcionar conforto, alegria e dignidade para aqueles que talvez nunca encontrem uma família. </p>

        </div>
        <div class="col-md-5 order-md-1">
            <div class="bd-placeholder-img-lg featurette-image img-fluid mx-auto">
                <img src="{% static 'core/img/abrigo_mulher.jpg' %}" alt="..." class="img-fluid">
            </div>
        </div>
    </div>
</div>
{% endblock %}